/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/B-03.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0.14, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3609.geometry}
          material={materials["FI_Wood Floor"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3610.geometry}
          material={materials["FI_Wood Floor"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle1174505049.geometry}
          material={materials["FI_Wood Floor"]}
        />
      </group>
      <group rotation={[0, 0.14, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3611.geometry}
          material={materials["FI_Wood Floor"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3612.geometry}
          material={materials["FI_Wood Floor"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle1174505050.geometry}
          material={materials["FI_Wood Floor"]}
        />
      </group>
      <group rotation={[0, 0.14, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3613.geometry}
          material={materials["FI_Wood Floor"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3614.geometry}
          material={materials["FI_Wood Floor"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle1174505051.geometry}
          material={materials["FI_Wood Floor"]}
        />
      </group>
      <group rotation={[0, 0.14, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3615.geometry}
          material={materials["FI_Wood Floor"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Line3616.geometry}
          material={materials["FI_Wood Floor"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle1174505052.geometry}
          material={materials["FI_Wood Floor"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3598.geometry}
        material={materials["FI_Wood Floor"]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3599.geometry}
        material={materials["FI_Wood Floor"]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3600.geometry}
        material={materials["FI_Wood Floor"]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3601.geometry}
        material={materials["FI_Wood Floor"]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3602.geometry}
        material={materials["FI_Wood Floor"]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3603.geometry}
        material={materials["FI_Wood Floor"]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3604.geometry}
        material={materials["FI_Wood Floor"]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3605.geometry}
        material={materials["FI_Wood Floor"]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3606.geometry}
        material={materials["FI_Wood Floor"]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3607.geometry}
        material={materials["FI_Wood Floor"]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3608.geometry}
        material={materials["FI_Wood Floor"]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3617.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3618.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3619.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3620.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3621.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3622.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3623.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3624.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3625.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3626.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3627.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3628.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3629.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3630.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3631.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3632.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3633.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3634.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3635.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3636.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3637.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3638.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3639.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3640.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3641.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3642.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3643.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3644.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3645.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3646.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3647.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3648.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3649.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3650.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3651.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3652.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3653.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3654.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3655.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3656.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3657.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3658.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3659.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3660.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3661.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3662.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3663.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3664.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3665.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3666.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3667.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3668.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3669.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3670.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3671.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3672.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3673.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3674.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3675.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3676.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3677.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3678.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3679.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3680.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3681.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3682.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3683.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3684.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3685.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3686.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3687.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3688.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3689.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3690.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3691.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3692.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3693.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3694.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3695.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3696.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3697.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3698.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3699.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3700.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3701.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3702.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3703.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3704.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3705.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3706.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3707.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3708.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3709.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3710.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3711.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3712.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3713.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3714.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3715.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3716.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3717.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3718.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3719.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3720.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3721.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3722.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3723.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3724.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3725.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3726.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3727.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3728.geometry}
        material={materials["FI_Material #-2147483642"]}
        rotation={[Math.PI, -0.133, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box668437.geometry}
        material={materials["FI_Material #2147483646"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3729.geometry}
        material={materials["FI_Material #2147483646"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3730.geometry}
        material={materials["FI_Material #2147483646"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3731.geometry}
        material={materials["FI_Material #2147483646"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3732.geometry}
        material={materials["FI_Material #2147483646"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3733.geometry}
        material={materials["FI_Material #2147483646"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3734.geometry}
        material={materials["FI_Material #2147483646"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3735.geometry}
        material={materials["FI_Material #2147483646"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3736.geometry}
        material={materials["FI_Material #-2147483645"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3737.geometry}
        material={materials["FI_Material #-2147483645"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3738.geometry}
        material={materials["FI_Material #-2147483645"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3739.geometry}
        material={materials["FI_Material #-2147483645"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3740.geometry}
        material={materials["FI_Material #-2147483645"]}
        rotation={[-Math.PI, 1.438, -Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3741.geometry}
        material={materials["FI_Material #-2147483645"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3742.geometry}
        material={materials["FI_Material #-2147483645"]}
        rotation={[0, -1.438, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3743.geometry}
        material={materials["FI_Material #-2147483645"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3744.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3745.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3746.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line3747.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2131.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2132.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2133.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2134.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2135.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2137.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2138.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, -1.438, -Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2139.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, -1.438, -Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2140.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, -1.438, -Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2141.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, -1.438, -Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2142.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, -Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2143.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2144.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, -1.438, -Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2145.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, -1.438, -Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2146.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, -1.438, -Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2147.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, -1.438, -Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2148.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, -1.438, -Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2149.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, -1.438, -Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2150.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2151.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, -Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2152.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2153.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2154.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2155.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2156.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2157.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2158.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2159.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2160.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2161.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2162.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2163.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials["FI_Material #2147483646.001"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2164.geometry}
        material={materials["FI_Material #496"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2165.geometry}
        material={materials["FI_Material #496"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2166.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2167.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2168.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2169.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2170.geometry}
        material={materials["FI_Material #496"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2171.geometry}
        material={materials["FI_Material #496"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2172.geometry}
        material={materials["FI_Material #496"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2173.geometry}
        material={materials["FI_Material #496"]}
        rotation={[0, -1.438, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2174.geometry}
        material={materials["FI_Material #496"]}
        rotation={[0, -1.438, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2175.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object2176.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI, 1.438, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PivotDoor005.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, 3.009]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PivotDoor006.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, 3.009]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PivotDoor007.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -0.133]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PivotDoor008.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -0.133]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={materials["FI_Material #496"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010.geometry}
        material={materials["FI_Material #496"]}
        rotation={[0, 0.133, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials["FI_Material #496"]}
        rotation={[-Math.PI, 1.438, -Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI, -0.133, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={materials["FI_Material #496"]}
        rotation={[-Math.PI, 1.438, -Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow039.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -1.703]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow040.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -1.703]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow041.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -1.703]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow042.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -1.703]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow043.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -1.703]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow044.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -0.133]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow045.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -0.133]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow046.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -0.133]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow047.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -0.133]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow048.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -0.133]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow049.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -0.133]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow050.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -0.133]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow051.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -0.133]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow052.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, 3.009]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow053.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, 3.009]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow054.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, 3.009]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow055.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, 3.009]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow056.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, 3.009]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow057.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, 3.009]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow058.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, 3.009]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow059.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, 3.009]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow060.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, 3.009]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow061.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, 3.009]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow062.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, 1.438]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow063.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, 1.438]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow064.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -1.703]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow065.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -1.703]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow066.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -1.703]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow067.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, 3.009]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow068.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, 3.009]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow069.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, 3.009]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow070.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -0.133]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow071.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -0.133]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow072.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -0.133]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow073.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, 3.009]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow074.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, 3.009]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SlidingWindow075.geometry}
        material={materials["FI_Material #496"]}
        rotation={[Math.PI / 2, 0, -0.133]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/B-03.glb");
